server
{
	listen 127.0.0.1:8085;
	server_name localhost;

	location /
	{
		root files;
		index index.html;
		allow_methods GET POST;
	}

	location /cgi
	{
		root cgi;
		cgi_pass php-cgi;
		allow_methods GET POST;
	}
}