server
{
	listen 127.0.0.1:8080;
	server_name localhost;

	error_page 400 files/error_400.html;
	error_page 403 files/error_403.html;
	error_page 404 files/error_404.html;
	error_page 405 files/error_405.html;
	error_page 413 files/error_413.html;
	error_page 500 files/error_500.html;

	client_max_body_size 1M;

	location /
	{
		root files;
		index index.html;
		autoindex on;
		allow_methods GET POST DELETE;
	}

	location /images
	{
		root files;
		autoindex on;
		allow_methods GET;
	}

	location /uploads
	{
		root uploads;
		allow_methods GET POST DELETE;
		upload_store uploads;
		autoindex on;
	}
}

server
{
	listen 127.0.0.1:8081;
	server_name localhost;

	error_page 400 files/error_400.html;
	error_page 403 files/error_403.html;
	error_page 404 files/error_404.html;
	error_page 405 files/error_405.html;
	error_page 413 files/error_413.html;
	error_page 500 files/error_500.html;

	client_max_body_size 1M;

	location /
	{
		root files;
		index index1.html;
		autoindex on;
		allow_methods GET POST DELETE;
	}

	location /uploads
	{
		root uploads;
		allow_methods GET POST DELETE;
		upload_store uploads;
	}
}