server
{
	listen 127.0.0.1:8080;
	server_name localhost;

	error_page 400 files/error_pages/400.html;
	error_page 403 files/error_pages/403.html;
	error_page 404 files/error_pages/404.html;
	error_page 405 files/error_pages/405.html;
	error_page 413 files/error_pages/413.html;
	error_page 500 files/error_pages/500.html;

	client_max_body_size 1M;

	location /
	{
		root files;
		index index.html;
		autoindex on;
		allow_methods GET POST DELETE;
	}

	location /uploads
	{
		root uploads;
		allow_methods GET POST DELETE;
		upload_store uploads;
	}

	# location /files/cgi
	# {
	# 	root ./files/cgi;
	# 	allow_methods GET POST;
	# 	cgi_extension .py;
	# 	cgi_path /usr/bin/python3;
	# }

	location /files/cgi
	{
		cgi_extension .php;
		cgi_path /usr/bin/php-cgi;
		root /home/ddo-carm/Desktop/webserv/files/cgi
		allow_methods GET POST;
	}
}

server
{
	listen 127.0.0.1:8081;
	server_name localhost;

	error_page 400 files/error_pages/400.html;
	error_page 403 files/error_pages/403.html;
	error_page 404 files/error_pages/404.html;
	error_page 405 files/error_pages/405.html;
	error_page 413 files/error_pages/413.html;
	error_page 500 files/error_pages/500.html;

	client_max_body_size 1M;

	location /
	{
		root files;
		index index1.html;
		autoindex on;
		allow_methods GET POST DELETE;
	}

	location /uploads
	{
		root uploads;
		allow_methods GET POST DELETE;
		upload_store uploads;
	}
}
